[tools]
# Required tools
go = "1.23.0"
task = "3.37.2"

# Go tools
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "1.57.2"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "1.27.0"
"go:go.uber.org/mock/mockgen" = "0.5.0"
"go:github.com/air-verse/air" = "1.61.7"
"go:github.com/mitranim/gow" = "latest"

[tasks]
generate = "task generate"
clean = "task clean"

[env]

POSTMARK_SERVER_TOKEN = "21a48da3-5111-40ce-b8f0-7ac978327fd2"
POSTMARK_EMAIL_FROM = "noreply@tofudns.net"
