version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tofudns
      POSTGRES_PASSWORD: tofudns
      POSTGRES_DB: tofudns
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
