services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tofudns
      POSTGRES_PASSWORD: tofudns
      POSTGRES_DB: tofudns
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - tofudns

  coredns:
    image: ghcr.io/tofudns/coredns:1.12.0-postgresql
    depends_on:
      - postgres
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./config/Corefile:/Corefile
    restart: always
    networks:
      - tofudns

  tofudns:
    image: ghcr.io/tofudns/tofudns:latest
    depends_on:
      - postgres
      - coredns
    restart: always
    networks:
      - tofudns

networks:
  tofudns:
    driver: bridge 
