services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tofudns
      POSTGRES_PASSWORD: tofudns
      POSTGRES_DB: tofudns
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - tofudns

  coredns:
    image: ghcr.io/tofudns/coredns:1.12.0-postgresql
    depends_on:
      - postgres
    expose:
      - "53"
      - "53/udp"
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./config/Corefile:/Corefile
    networks:
      - tofudns

  testing:
    build:
      context: .
      dockerfile: Dockerfile.testing
    depends_on:
      - coredns
      - postgres
    networks:
      - tofudns

networks:
  tofudns:
    driver: bridge
