version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tofudns
      POSTGRES_PASSWORD: tofudns
      POSTGRES_DB: tofudns
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  coredns:
    image: ghcr.io/tofudns/coredns:1.12.0-postgresql
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - ./Corefile:/etc/coredns/Corefile
