version: '3'

tasks:
  generate:
    cmds:
      - go generate ./...

  clean:
    cmds:
      - rm -rf gen

  default:
    cmds:
      - task: generate

  build:
    cmds:
      - go build -o tofudns ./cmd/service/main.go

  compose:
    cmds:
      - task: "compose:{{.CLI_ARGS}}"

  compose:up:
    cmds:
      - docker compose up -d

  compose:down:
    cmds:
      - docker compose down

  run:
    cmds:
      - air
