version: '3'

vars:
  TOFUDNS_IMAGE: ghcr.io/tofudns/tofudns
  DOCKER_TAG: latest

tasks:
  generate:
    cmds:
      - go generate ./...

  clean:
    cmds:
      - rm -rf gen

  default:
    cmds:
      - task: generate

  build:
    cmds:
      - go build -o tofudns ./cmd/service/main.go

  compose:
    cmds:
      - task: "compose:{{.CLI_ARGS}}"

  compose:up:
    cmds:
      - docker compose up -d

  compose:up:debug:
    cmds:
      - docker compose up

  compose:down:
    cmds:
      - docker compose down

  compose:prod:up:
    cmds:
      - docker compose -f docker-compose.prod.yml up -d

  compose:prod:down:
    cmds:
      - docker compose -f docker-compose.prod.yml down

  run:
    cmds:
      - go mod tidy
      - go run ./cmd/service/main.go

  run:debug:
    cmds:
      - gow -e go,html,css,js,mod,sql run ./cmd/service/main.go

  docker:build:tofudns:
    cmds:
      - docker build -t {{.TOFUDNS_IMAGE}}:{{.DOCKER_TAG}} .

  docker:push:tofudns:
    cmds:
      - docker push {{.TOFUDNS_IMAGE}}:{{.DOCKER_TAG}}

  docker:all:
    deps: [docker:build:tofudns]
    cmds:
      - task: docker:push:tofudns

  test:dig:
    cmds:
      - docker exec -it tofudns-testing-1 dig @coredns -p 53 +short A example.org
