version: '3'

tasks:
  generate:
    cmds:
      - go generate ./...

  clean:
    cmds:
      - rm -rf gen

  default:
    cmds:
      - task: generate

  build:
    cmds:
      - go build -o tofudns ./cmd/service/main.go

  compose:
    cmds:
      - task: "compose:{{.CLI_ARGS}}"

  compose:up:
    cmds:
      - docker compose up -d

  compose:up:debug:
    cmds:
      - docker compose up

  compose:down:
    cmds:
      - docker compose down

  run:
    cmds:
      - go mod tidy
      - air

  test:dig:
    cmds:
      - docker exec -it tofudns-testing-1 dig @coredns -p 53 +short A example.org
