// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"context"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg CreateRecordParams) (CorednsRecord, error)
	DeleteRecord(ctx context.Context, arg DeleteRecordParams) error
	GetRecordByID(ctx context.Context, arg GetRecordByIDParams) (CorednsRecord, error)
	ListRecords(ctx context.Context, zone string) ([]CorednsRecord, error)
	ListRecordsByName(ctx context.Context, arg ListRecordsByNameParams) ([]CorednsRecord, error)
	ListRecordsByType(ctx context.Context, arg ListRecordsByTypeParams) ([]CorednsRecord, error)
	ListRecordsByZone(ctx context.Context, zone string) ([]CorednsRecord, error)
	UpdateRecord(ctx context.Context, arg UpdateRecordParams) (CorednsRecord, error)
}

var _ Querier = (*Queries)(nil)
